export { default as Hero } from './Hero'
export { default as HowItWorks } from './HowItWorks'
export { default as Products } from './Products'
export { default as Demo } from './Demo'
export { default as FAQ } from './FAQ'
